# yaml-language-server: $schema=https://coderabbit.ai/integrations/coderabbit-overrides.v2.json
language: "en" # English
early_access: false
reviews:
  high_level_summary: false # Disable the high level summary because this feature modifies the original PR description. Ideally this feature would add a new comment to the PR instead of modifying the original PR description.
  poem: false # Disable the poem feature because it adds noise and doesn't improve the review process.
  review_status: false
  collapse_walkthrough: true
  path_filters: []
  path_instructions: []
  auto_review:
    enabled: false
    drafts: false
    base_branches: []
chat:
  auto_reply: false