steps:
- task: AzureCLI@2
  displayName: 'Show managed identity details'
  inputs:
    azureSubscription: 'azure-vsce-publish'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show --output json
