- task: AzureCLI@2
  displayName: 'Get DevOps identity id'
  inputs:
    azureSubscription: 'azure-vsce-publish'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az rest \
        --method get \
        --uri https://app.vssps.visualstudio.com/_apis/profile/profiles/me?api-version=7.1-preview.3 \
        --output json
