TARGET = cxx
TYPE = ps-exe

CXXFLAGS = -std=c++17

SRCS = \
../common/syscalls/printf.s \
../common/crt0/crt0cxx.s \
../common/crt0/cxxglue.c \
../common/crt0/memory-c.c \
../common/crt0/memory-s.s \
main.cpp \

include ../common.mk
