#!/usr/bin/env python3
"""Emit job.h for the MDEC roundtrip rig.

The job is baked into the executable. That started as a workaround for PCopen
returning -1 on the farm while PCcreat succeeded, and THAT DIAGNOSIS WAS WRONG:
PCDRV is complete and the protocol is fine; the runner-agent had no references to
input_fileset, so assets attached with --asset were resolved, digest-pinned,
shipped and then dropped. Fixed in the farm's f9d1c4f. Baking it in is kept
because it makes a run self-contained and identical under the emulator, not
because the read half is missing.
"""
import struct, sys

STD = [0x5A82]*8 + [0x7D8A,0x6A6D,0x471C,0x18F8,0xE707,0xB8E3,0x9592,0x8275] \
    + [0x7641,0x30FB,0xCF04,0x89BE,0x89BE,0xCF04,0x30FB,0x7641] \
    + [0x6A6D,0xE707,0x8275,0xB8E3,0x471C,0x7D8A,0x18F8,0x9592] \
    + [0x5A82,0xA57D,0xA57D,0x5A82,0x5A82,0xA57D,0xA57D,0x5A82] \
    + [0x471C,0x8275,0x18F8,0x6A6D,0x9592,0xE707,0x7D8A,0xB8E3] \
    + [0x30FB,0x89BE,0x7641,0xCF04,0xCF04,0x7641,0x89BE,0x30FB] \
    + [0x18F8,0xB8E3,0x6A6D,0x8275,0x7D8A,0x9592,0x471C,0xE707]
STD = [v - 0x10000 if v > 0x7fff else v for v in STD]

def build(arm):
    upload = arm != 'A'
    st = list(STD)
    if arm == 'D': st[0] += 1                      # forces the general path, basis ~unchanged
    if arm == 'B': st = [v // 2 for v in st]       # halved basis
    dc = [200, -150, 300, -80, 120, -40]
    rl = []
    for b in range(6):
        rl += [((8 & 0x3f) << 10) | (dc[b] & 0x3ff),
               (0 << 10) | (90 & 0x3ff),
               (2 << 10) | ((-60) & 0x3ff),
               0xFE00]
    # psx-spx: "DMA0 and DMA1 should be usually used with a blocksize of 20h words.
    # If necessary, the parameters for the MDEC(1) command should be padded with
    # FE00h halfwords to match the 20h words (40h halfwords) DMA blocksize."
    # 40h HALFWORDS, not 20h. Padding to 32 halfwords leaves a 16-word transfer,
    # whose block count (words/32) rounds to ZERO and hangs DMA0 on real hardware.
    while len(rl) % 64: rl.append(0xFE00)
    return upload, st, rl

# R arms probe whether an MDEC reset clears the uploaded tables. All of them
# upload the STANDARD scale table first, so a table that survives reset yields
# the known-good image and a table that does not yields flat grey.
#   R1 reset, then decode                    R3 reset, re-upload scale only
#   R2 reset, re-upload quant only           R4 reset, re-upload both (control)
RESET_MODE = {'R1': 1, 'R2': 2, 'R3': 3, 'R4': 4}

arm = sys.argv[1]
reset = RESET_MODE.get(arm, 0)
upload, st, rl = build('C' if arm.startswith('R') else arm)
out = [f'// Generated by genjob.py {arm} - do not edit.', '#pragma once', '#include <stdint.h>', '']
out.append(f'#define JOB_ARM "{arm}"')
out.append(f'#define JOB_UPLOAD_SCALE {1 if upload else 0}')
out.append(f'#define JOB_RESET_MODE {reset}')
out.append(f'#define JOB_RL_WORDS {len(rl)}')
out.append('static const uint8_t job_quant[128] = {' + ','.join(['1']*128) + '};')
out.append('static const int16_t job_scale[64] = {' + ','.join(str(v) for v in st) + '};')
out.append('static const uint16_t job_rl[%d] = {' % len(rl) + ','.join(str(v) for v in rl) + '};')
open('job.h','w').write('\n'.join(out) + '\n')
print(f'job.h: arm {arm}, upload={upload}, reset_mode={reset}, {len(rl)} rl words, scale[0]={st[0]}')
