TARGET = ucl-demo
TYPE = ps-exe

SRCS = \
ucl-demo.cpp \
n2e-d.S \
../psyqo/src/adler32.cpp \
../common/syscalls/printf.s \
../common/crt0/crt0.s \

CPPFLAGS = -I../../../third_party/EASTL/include -I../../../third_party/EABase/include/Common

include ../common.mk
