all:
	$(MAKE) -C basic all
	$(MAKE) -C cdrom all
	$(MAKE) -C cop0 all
	$(MAKE) -C cpu all
	$(MAKE) -C libc all
	$(MAKE) -C pcdrv all
	$(MAKE) -C dma all

clean:
	$(MAKE) -C basic clean
	$(MAKE) -C cdrom clean
	$(MAKE) -C cop0 clean
	$(MAKE) -C cpu clean
	$(MAKE) -C libc clean
	$(MAKE) -C pcdrv clean
	$(MAKE) -C dma clean
