all:
	$(MAKE) -C basic all
	$(MAKE) -C cpu all
	$(MAKE) -C cop0 all
	$(MAKE) -C dma all
	$(MAKE) -C libc all
	$(MAKE) -C memcpy all
	$(MAKE) -C memset all
	$(MAKE) -C pcdrv all

clean:
	$(MAKE) -C basic clean
	$(MAKE) -C cpu clean
	$(MAKE) -C cop0 clean
	$(MAKE) -C dma clean
	$(MAKE) -C libc clean
	$(MAKE) -C memcpy clean
	$(MAKE) -C memset clean
	$(MAKE) -C pcdrv clean
