all:
	$(MAKE) -C basic all
	$(MAKE) -C libc all
	$(MAKE) -C cpu all
	$(MAKE) -C cop0 all
	$(MAKE) -C pcdrv all

clean:
	$(MAKE) -C basic clean
	$(MAKE) -C libc clean
	$(MAKE) -C cpu clean
	$(MAKE) -C cop0 clean
	$(MAKE) -C pcdrv clean
