all:
	$(MAKE) -C bank-probe all
	$(MAKE) -C display-area-y all
	$(MAKE) -C drawing-area-y all
	$(MAKE) -C drawing-offset-y all
	$(MAKE) -C fast-fill-h-quirk all
	$(MAKE) -C fast-fill-y all
	$(MAKE) -C gp1-09-matrix all
	$(MAKE) -C primitives-cross all
	$(MAKE) -C transfer-h-quirk all
	$(MAKE) -C vram-blit-y all
	$(MAKE) -C vram-transfers-y all

clean:
	$(MAKE) -C bank-probe clean
	$(MAKE) -C display-area-y clean
	$(MAKE) -C drawing-area-y clean
	$(MAKE) -C drawing-offset-y clean
	$(MAKE) -C fast-fill-h-quirk clean
	$(MAKE) -C fast-fill-y clean
	$(MAKE) -C gp1-09-matrix clean
	$(MAKE) -C primitives-cross clean
	$(MAKE) -C transfer-h-quirk clean
	$(MAKE) -C vram-blit-y clean
	$(MAKE) -C vram-transfers-y clean
