TARGET = psyqo-tests
TYPE = ps-exe

SRCS = \
psyqo-tests.cpp \
test-fixed-point.cpp \
test-vector.cpp \
test-trigonometry.cpp \
test-soft-math.cpp \
test-msf.cpp \
test-adler32.cpp \
test-bezier.cpp \
test-primitives.cpp \

CXXFLAGS = -std=c++20

include ../../psyqo/snitch.mk
