TARGET = {{projectName}}
TYPE = ps-exe

SRCS = \
third_party/nugget/common/syscalls/printf.c \
third_party/nugget/common/crt0/crt0.s \
third_party/nugget/common/crt0/memory-c.c \
third_party/nugget/common/crt0/memory-s.s \
main.c

include third_party/nugget/common.mk
