TARGET = tetris
TYPE = ps-exe

SRCS = \
credits.cpp \
game.cpp \
gameover.cpp \
mainmenu.cpp \
options.cpp \
pause.cpp \
pieces.cpp \
rand.cpp \
splash.cpp \
tetris.cpp \

CPPFLAGS = -Werror
CXXFLAGS = -std=c++20

include ../../psyqo.mk
