#!/usr/bin/env python3
# Generates bsdec-vlc.h: the clz-dispatch decode tables for Sony's standard MDEC
# AC code book (FileFormat47 Table 1-7).
#
# The code book is NOT transcribed here. It is read out of src/supportpsx/dct.cc,
# whose copy is the one graded against Sony's own DecDCTvlc on 7303 retail frames.
# One source, one validated copy, no second transcription to get wrong.
#
# Run from the repo root:  python3 -P src/mips/bsdec/gentable.py
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
# The code book is read out of dct.cc so there is one copy of it in the tree. On a
# branch that does not carry the encoder yet, point BSDEC_DCT_ROOT at a checkout
# that does; the tables it generates are identical either way.
SRC = os.path.join(os.environ.get('BSDEC_DCT_ROOT', ROOT), 'src', 'supportpsx', 'dct.cc')
OUT = os.path.join(ROOT, 'src', 'mips', 'bsdec', 'bsdec-vlc.h')

src = open(SRC).read()

m = re.search(r'c_vlcMaxLevel\[32\]\s*=\s*\{([^}]*)\}', src)
maxlvl = [int(x) for x in m.group(1).split(',')]
assert len(maxlvl) == 32

m = re.search(r'c_vlcRun\[32\]\[40\]\s*=\s*\{(.*?)\n\};', src, re.S)
pairs = re.findall(r'\{\s*(0x[0-9a-fA-F]+|0)\s*,\s*(\d+)\s*\}', m.group(1))
assert len(pairs) == 32 * 40, len(pairs)


def cell(r, c):
    v, b = pairs[r * 40 + c]
    return (int(v, 16) if v.startswith('0x') else int(v)), int(b)


def one(pat, name):
    mm = re.search(pat, src)
    return int(mm.group(1), 16), int(mm.group(2))


EOB = one(r'c_vlcEob\s*=\s*\{\s*(0x[0-9a-fA-F]+)\s*,\s*(\d+)\s*\}', 'eob')
ESC = one(r'c_vlcEsc\s*=\s*\{\s*(0x[0-9a-fA-F]+)\s*,\s*(\d+)\s*\}', 'esc')

# kind: 0 normal, 1 eob, 2 escape
syms = []
syms.append((format(EOB[0], '0%db' % EOB[1]), 1, 0, 0))
syms.append((format(ESC[0], '0%db' % ESC[1]), 2, 0, 0))
for r in range(32):
    for l in range(1, maxlvl[r] + 1):
        c, b = cell(r, l - 1)
        assert b, 'hole in the code book at run %d level %d' % (r, l)
        syms.append((format(c, '0%db' % b), 0, r, l))
        syms.append((format(c | 1, '0%db' % b), 0, r, -l))

codes = [s[0] for s in syms]
assert len(set(codes)) == len(codes), 'duplicate code'
for a in codes:
    for b in codes:
        if a is not b and b.startswith(a):
            sys.exit('code book is not prefix-free: %s is a prefix of %s' % (a, b))

MAXNZ = max(len(c) - len(c.lstrip('0')) for c in codes)
groups = [[] for _ in range(MAXNZ + 1)]
for c, kind, run, lvl in syms:
    n = len(c) - len(c.lstrip('0'))
    assert c[n] == '1', 'code %s does not have a marker 1 after its leading zeros' % c
    groups[n].append((c, kind, run, lvl))
for n, g in enumerate(groups):
    assert g, 'leading-zero count %d has no codes: the dispatch would have a hole' % n

# Per group, the suffix after the marker 1. Widen to the longest code in the group and
# resolve the short ones by covering every suffix they prefix.
widths = [max(len(c) - n - 1 for c, _, _, _ in g) for n, g in enumerate(groups)]
tables = []
offsets = []
total = 0
for n, g in enumerate(groups):
    w = widths[n]
    offsets.append(total)
    slots = [None] * (1 << w)
    for c, kind, run, lvl in g:
        suf = c[n + 1:]
        nbits = len(suf)
        base = int(suf, 2) if nbits else 0
        # every wider suffix this code is a prefix of
        for extra in range(1 << (w - nbits)):
            idx = (base << (w - nbits)) | extra
            assert slots[idx] is None, 'ambiguous slot n=%d idx=%d' % (n, idx)
            slots[idx] = (kind, run, lvl, nbits)
    tables.append(slots)
    total += len(slots)

# entry: bits 0..15 the MDEC run-level halfword, 16..20 suffix bits to consume,
#        21..22 kind, 23 valid
INVALID = 0


def pack(e):
    if e is None:
        return INVALID
    kind, run, lvl, nbits = e
    if kind == 1:
        hw = 0xfe00
    elif kind == 2:
        hw = 0
    else:
        hw = ((run & 0x3f) << 10) | (lvl & 0x3ff)
    assert nbits <= 31
    return hw | (nbits << 16) | (kind << 21) | (1 << 23)


holes = sum(1 for t in tables for e in t if e is None)
with open(OUT, 'w') as f:
    f.write('''// GENERATED by src/mips/bsdec/gentable.py - do not edit.
//
// Sony's standard MDEC AC code book (FileFormat47 Table 1-7), rearranged for a
// count-leading-zeros dispatch. Every code in the book is N zeros, a marker 1, then a
// suffix whose width depends only on N, so one clz plus one indexed load replaces the
// bit-at-a-time walk down a trie.
//
//   n     codes  code lengths  suffix width
''')
    for n, g in enumerate(groups):
        f.write('//   %-5d %-6d %-13s %d\n' % (n, len(g), sorted(set(len(c) for c, _, _, _ in g)), widths[n]))
    f.write('//\n// %d symbols, %d table slots, %d unreachable (invalid prefixes).\n' % (len(syms), total, holes))
    f.write('''//
// Entry layout, chosen so the common path is one load and one mask:
//   bits  0..15  the MDEC run-level halfword, ready to store (0xfe00 for EOB)
//   bits 16..20  suffix bits to consume after the marker 1
//   bits 21..22  kind: 0 normal, 1 end of block, 2 escape
//   bit  23      set on a valid entry; a zero word is an invalid prefix

#pragma once

#include <stdint.h>

#define BSDEC_VLC_MAXNZ %d

#define BSDEC_VLC_HALFWORD(e) ((uint16_t)((e) & 0xffff))
#define BSDEC_VLC_SUFFIXBITS(e) (((e) >> 16) & 0x1f)
#define BSDEC_VLC_KIND(e) (((e) >> 21) & 3)
#define BSDEC_VLC_VALID(e) ((e) & (1 << 23))

#define BSDEC_VLC_NORMAL 0
#define BSDEC_VLC_EOB 1
#define BSDEC_VLC_ESCAPE 2

''' % MAXNZ)
    # PADDED TO 32 ENTRIES ON PURPOSE. bsdecClz32 reports 0..31, and the decoder
    # used to spend a compare-and-branch per symbol rejecting n > MAXNZ. The
    # stream is the user's own data, so a malformed prefix does not need
    # detecting, it needs to stop costing a branch: rows MAXNZ+1..31 carry width
    # 0 and point at a sentinel EOB slot appended to the table, so garbage ends
    # the block through the ordinary end-of-block path with no test at all.
    pad = 32 - len(widths)
    f.write('/* Rows past %d are the garbage-prefix sentinel: width 0, pointing at\n'
            '   the appended EOB slot, so an impossible prefix needs no bounds test. */\n' % MAXNZ)
    f.write('static const uint8_t c_bsdecVlcSuffixBits[32] = {%s};\n\n'
            % ', '.join(str(w) for w in list(widths) + [0] * pad))
    f.write('static const uint16_t c_bsdecVlcOffset[32] = {%s};\n\n'
            % ', '.join(str(o) for o in list(offsets) + [total] * pad))
    f.write('static const uint32_t c_bsdecVlc[%d] = {\n' % (total + 1))
    for n, t in enumerate(tables):
        f.write('    // n = %d, suffix %d bits\n' % (n, widths[n]))
        line = '   '
        for e in t:
            tok = ' 0x%08x,' % pack(e)
            if len(line) + len(tok) > 118:
                f.write(line + '\n')
                line = '   '
            line += tok
        f.write(line + '\n')
    f.write('    // sentinel: every prefix longer than the book ends the block here\n')
    f.write('    0x%08x,\n' % pack((1, 0, 0, 0)))  # kind 1 = EOB, no suffix
    f.write('};\n')

# The version-3 delta-DC size books, read out of the same file for the same reason.
# These are MPEG-1's DC size codes (ISO/IEC 11172-2 tables B-12 and B-13); Sony's
# DecDCTvlc derives the long ones arithmetically rather than tabulating them.
def dcbook(name):
    mm = re.search(r'%s\[9\]\s*=\s*\{(.*?)\};' % name, src, re.S)
    ent = re.findall(r'\{\s*(0b[01]+)\s*,\s*(\d+)\s*\}', mm.group(1))
    assert len(ent) == 9, (name, len(ent))
    out = []
    for v, b in ent:
        code, bits = int(v, 2), int(b)
        assert code < (1 << bits), (name, v, b)
        out.append((code, bits))
    return out


luma = dcbook('c_dcSizeLuma')
chroma = dcbook('c_dcSizeChroma')
for nm, bk in (('luma', luma), ('chroma', chroma)):
    pats = [format(c, '0%db' % b) for c, b in bk]
    for a in pats:
        for c in pats:
            if a is not c and c.startswith(a):
                sys.exit('%s DC size book is not prefix-free: %s prefixes %s' % (nm, a, c))

with open(OUT, 'a') as f:
    f.write("""
// Version-3 delta-DC size books, indexed by size 0..8: MPEG-1's DC size codes
// (ISO/IEC 11172-2 tables B-12 and B-13). Blocks 0 and 1 of a macroblock are Cr and
// Cb and take the chroma book; blocks 2..5 are luma and share the other one. Both
// are prefix-free, checked at generation time, so a linear walk resolves them
// without caring about the order.
""")
    for nm, bk in (('Luma', luma), ('Chroma', chroma)):
        f.write('static const uint8_t c_bsdecDc%sCode[9] = {%s};\n'
                % (nm, ', '.join('0x%02x' % c for c, _ in bk)))
        f.write('static const uint8_t c_bsdecDc%sBits[9] = {%s};\n'
                % (nm, ', '.join(str(b) for _, b in bk)))
print('DC size books: luma %s chroma %s' % ([b for _, b in luma], [b for _, b in chroma]))
print('wrote %s: %d symbols, %d slots, %d invalid, maxnz %d' % (OUT, len(syms), total, holes, MAXNZ))
print('suffix widths:', widths)
