TARGET = fast-fill-h-quirk
TYPE = ps-exe

SRCS += \
../../../common/syscalls/printf.s \
../../../common/crt0/memory-s.s \
../../../common/crt0/memory-c.c \
../../../common/crt0/crt0.s \
fast-fill-h-quirk.c \

CPPFLAGS = -I..

include ../../../common.mk
