local root = path.join(os.scriptdir(), '..', '..', '..')
local mips = path.join(os.scriptdir(), '..')
local psyqo = path.join(os.scriptdir())

set_allowedmodes('debug', 'dev', 'release')
includes(mips)

set_languages('c++26')

target('psyqo', function()
    set_kind('static')
    add_rules('nugget')
    add_files(path.join(psyqo, 'src', '*.c'))
    add_files(path.join(psyqo, 'src', '*.cpp'))
    add_files(path.join(psyqo, 'src', '**/*.cpp'))
    add_files(path.join(mips, 'common', 'hardware', 'flushcache.s'))
    add_files(path.join(mips, 'common', 'psxlibc', 'ucontext.s'))
    add_files(path.join(mips, 'common', 'util', '*.cc'))
    add_files(path.join(root, 'third_party', 'EASTL', 'source', '*.cpp'))
    add_includedirs(path.join(root, 'third_party', 'EASTL', 'include'), { public = true })
    add_includedirs(path.join(root, 'third_party', 'EABase', 'include', 'Common'), { public = true })
end)

rule('psyqo.app', function()
    add_deps('nugget')
    on_load(function(target)
        target:add('values', 'c++', true)
        target:set('kind', 'binary')
        target:add('deps', 'psyqo')
    end)
end)
