local root = path.join(os.scriptdir(), "..", "..", "..")
local mips = path.join(os.scriptdir(), "..")
local psyqo = path.join(os.scriptdir())

set_allowedmodes("debug", "dev", "release")
includes(mips)

set_languages("c11", "c++26")

rule("psyqo.app", function ()
    add_deps("nugget")
    on_load(function(target)
        target:add("values", "c++", true)
        target:set("kind", "binary")
        target:add("files", path.join(psyqo, "src", "*.c"))
        target:add("files", path.join(psyqo, "src", "*.cpp"))
        target:add("files", path.join(psyqo, "src", "**/*.cpp"))
        target:add("files", path.join(mips, "common", "hardware", "flushcache.s"))
        target:add("files", path.join(mips, "common", "psxlibc", "ucontext.s"))
        target:add("files", path.join(mips, "common", "util", "*.cc"))
        target:add("files", path.join(root, "third_party", "EASTL", "source", "*.cpp"))
        target:add("includedirs", path.join(root, "third_party", "EASTL", "include"))
        target:add("includedirs", path.join(root, "third_party", "EABase", "include", "Common"))
    end)
end)
