#!/usr/bin/env python3
# Regenerates sjis-encode-table.h: the inverse of sjis-table.h (Unicode -> Shift-JIS).
# The forward table is indexed by a remapped Shift-JIS codepoint (single bytes at
# 0x000-0x0ff; lead 0x80-0x8f at base 0x100; lead 0x90-0x9f at base 0x1100;
# lead 0xe0-0xef at base 0x2100; index = base + ((lead & 0xf) << 8) + trail).
# We walk every forward entry, reconstruct its Shift-JIS bytes, and keep the
# lowest Shift-JIS code per Unicode value (so single-byte forms win over
# double-byte). Run from the repo root.
import re, sys

fwd = [int(x, 16) for x in
       re.findall(r'0x[0-9a-fA-F]{4}', open('src/mips/common/util/sjis-table.h').read())]

def index_to_sjis(index):
    if index < 0x100:
        return index
    if index < 0x1100:   base, lead_hi = 0x100,  0x80
    elif index < 0x2100: base, lead_hi = 0x1100, 0x90
    else:                base, lead_hi = 0x2100, 0xe0
    r = index - base
    return ((lead_hi | (r >> 8)) << 8) | (r & 0xff)

rev = {}
for index, uni in enumerate(fwd):
    sjis = index_to_sjis(index)
    if sjis >= 0x100:
        if uni == 0x0020:  # unmapped filler cells decode to space; skip them
            continue
        trail = sjis & 0xff
        if not (0x40 <= trail <= 0x7e or 0x80 <= trail <= 0xfc):
            continue
    rev.setdefault(uni, sjis)

items = sorted(rev.items())
with open('src/mips/common/util/sjis-encode-table.h', 'w') as f:
    f.write("#pragma once\n\n#include <stdint.h>\n\n")
    f.write("// Generated by gen-sjis-encode-table.py: the inverse of sjis-table.h.\n")
    f.write("// Each index maps a Unicode codepoint to its Shift-JIS encoding. The list is\n")
    f.write("// sorted by Unicode value for binary search. A Shift-JIS value <= 0xff is a\n")
    f.write("// single byte; otherwise it is two bytes, high byte first.\n\n")
    f.write("static const struct {\n    uint16_t unicode;\n    uint16_t sjis;\n} c_unicodeToSjisConvTable[] = {\n")
    line = "    "
    for uni, sjis in items:
        tok = "{0x%04x, 0x%04x}, " % (uni, sjis)
        if len(line) + len(tok) > 116:
            f.write(line.rstrip() + "\n"); line = "    "
        line += tok
    if line.strip():
        f.write(line.rstrip() + "\n")
    f.write("};\n")
print("emitted %d entries" % len(items), file=sys.stderr)
