name: Linux CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: grumpycoders/pcsx-redux-build:latest
      env:
        CC: clang-11
        CXX: clang++-11
        LD: clang++-11
        TEST_RESULTS: /tmp/test-results
        LLVM_PROFILE_FILE: /tmp/llvm_profile/profile-%p.profraw
        BUILD: Coverage
    steps:
      - uses: actions/checkout@v1
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - run: |
          make -j 2 all pcsx-redux-tests
          make -C src/mips/openbios -j 2
          cp src/mips/openbios/openbios.bin .
          make -C src/mips/openbios clean
          make -C src/mips/tests -j 2 PCSX_TESTS=true
          cp ./openbios.bin src/mips/openbios/
      - name: Test
        run: |
          xvfb-run catchsegv ./pcsx-redux-tests
      - name: Merge Code coverage
        run: |
          llvm-profdata-11 merge -sparse /tmp/llvm_profile/profile-*.profraw -o coverage.profdata
      - name: Convert Code coverage
        run: |
          llvm-cov-11 export --format=lcov ./pcsx-redux-tests -instr-profile=coverage.profdata > coverage.info
      - uses: codecov/codecov-action@v2
