name: macOS toolchain CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-build-and-test-toolchain:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
      with:
        set-safe-directory: true
    - name: Fetch submodules
      run: ./.github/scripts/update-submodules.sh
    - name: build mips binutils
      run: brew install --verbose pcsx-redux/mips/mipsel-none-elf-binutils
    - name: build mips gcc
      run: brew install --verbose pcsx-redux/mips/mipsel-none-elf-gcc
    - name: build openbios
      run: make -C ./src/mips/openbios