name: macOS toolchain CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macos-build-and-test-toolchain:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: build mips binutils
      run: brew install ./tools/macos-mips/mipsel-none-elf-binutils.rb --debug
    - name: build mips gcc
      run: brew install ./tools/macos-mips/mipsel-none-elf-gcc.rb --debug
    - name: build openbios
      run: make -C ./src/mips/openbios