name: macOS toolchain CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macos-build-and-test-toolchain:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        set-safe-directory: true
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: install dependencies
      run: brew install --verbose nikitabobko/tap/brew-install-path
    - name: build mips binutils
      run: brew install-path --verbose ./tools/macos-mips/mipsel-none-elf-binutils.rb
    - name: build mips gcc
      run: brew install-path --verbose ./tools/macos-mips/mipsel-none-elf-gcc.rb
    - name: build openbios
      run: make -C ./src/mips/openbios